#!/bin/bash
#PBS -N MinNet_SimpleSingle
#PBS -q cpu
#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=100:00:00
#PBS -J 1-8
#PBS -o logs/
#PBS -e logs/

cd $PBS_O_WORKDIR

module purge
module load compiler/anaconda3-23.07.0

source venv/bin/activate

TARGET=$(sed -n "${PBS_ARRAY_INDEX}p" kegg_core.txt)

python save_minimal_paths.py $TARGET simple_single

echo "Finished simple single pruning job for target: $TARGET at $(date)"
