#!/bin/bash
#PBS -N MinPath_Batch
#PBS -q cpu
#PBS -l select=1:ncpus=4:mem=32gb
#PBS -l walltime=10:00:00
#PBS -J 1-8
#PBS -o logs/
#PBS -e logs/

cd $PBS_O_WORKDIR

module purge
module load compiler/anaconda3-23.07.0

source venv/bin/activate

TARGET=$(sed -n "${PBS_ARRAY_INDEX}p" kegg_core.txt)

# arg1 = target molecule
# arg2 = batch or single
# arg3 = dataset number

python build_minimal_paths.py $TARGET batch 7

echo "Finished batch pruning job for target: $TARGET at $(date)"
