#!/bin/bash
#PBS -N RandAutoB_NP
#PBS -q cpu
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=250:00:00
#PBS -o logs/
#PBS -e logs/

cd $PBS_O_WORKDIR

module purge
module load compiler/anaconda3-23.07.0

source venv/bin/activate

# arg1 = single or batch
# arg2 = prune or noprune
# arg3 = dataset number
# arg4 = auto dataset number

python build_autonomous_networks.py NumPaths batch noprune 3 1

echo "Finished autonomous network generation at $(date)"