#!/bin/bash
#PBS -N PathRates
#PBS -q cpu
#PBS -l select=1:ncpus=8:mem=32gb
#PBS -l walltime=250:00:00
#PBS -J 1-8
#PBS -o logs/
#PBS -e logs/

cd $PBS_O_WORKDIR

module purge
module load compiler/anaconda3-23.07.0

source venv/bin/activate

TARGET=$(sed -n "${PBS_ARRAY_INDEX}p" kegg_core.txt)

python discover_paths.py $TARGET Batch

echo "Finished path discovery rate estimation for $TARGET at $(date)"
